feat: deployments and services
jriedel-ionos/grpc-deployer-operator pull request #1
Opened 2023-07-12 08:13 UTC by jriedel-ionos

2023-07-12 12:17 UTC, avorima requested changes
You broke kubebuilder compatibility by moving things around. It's fine that you use an internal package, but make sure that kubebuilder keeps working

2023-07-12 12:17 UTC, avorima commented on internal/controller/operator_controller.go
> +	if err := r.Get(ctx, key, deployment); err != nil {
You're repeating yourself quite often when deleting resources. Make use of the fact that everything is an "object" and create a generic deletion function with finalizer cleanup

2023-07-12 12:17 UTC, avorima commented on api/v1/operator_types.go
You usually don't do a `v1` when you start developing something.

2023-07-12 12:17 UTC, avorima commented on internal/controller/operator_controller.go
> +	return r.Client.Status().Update(ctx, operator)
What are these for?

2023-07-12 12:58 UTC, jonas27 commented
> You broke kubebuilder compatibility by moving things around. It's fine that you use an internal package, but make sure that kubebuilder keeps working

my personal preference for internal is: when in doubt opt out :wink:

2023-07-12 13:08 UTC, avorima commented
> > You broke kubebuilder compatibility by moving things around. It's fine that you use an internal package, but make sure that kubebuilder keeps working
> 
> my personal preference for internal is: when in doubt opt out wink

Actually, I didn't know that kubebuilder switched to this layout and thought that it just didn't work with `internal`. I have nothing against internal in general

2023-07-13 07:28 UTC, jonas27 commented
> > > You broke kubebuilder compatibility by moving things around. It's fine that you use an internal package, but make sure that kubebuilder keeps working
> > 
> > 
> > my personal preference for internal is: when in doubt opt out wink
> 
> Actually, I didn't know that kubebuilder switched to this layout and thought that it just didn't work with `internal`. I have nothing against internal in general

Its probably one of those topics where you could argue for weeks and in the end it doesn't matter. My two cents are that it encourages bad practices, like bad docs, naming, testing etc. because it cannot be used publicly. 
The only place I would use it is for APIs which are needed by the package structure to be package public but not public public. Most of the time it seems like extra caution where non is warranted.

2023-07-13 09:32 UTC, jriedel-ionos commented on internal/controller/operator_controller.go
> +	if err := r.Get(ctx, key, deployment); err != nil {
This should also be done for all `createOrUpdate...` functions, it's the same case. There could also be one generic function which seperates, i guess

2023-07-13 09:37 UTC, avorima commented on internal/controller/operator_controller.go
> +	if err := r.Get(ctx, key, deployment); err != nil {
you still need a custom mutator func so in the end you don't actually save any lines by doing something generic and could make things more complicated

2023-07-17 17:54 UTC, avorima commented on internal/controller/operator_controller.go
> +	controllerutil.RemoveFinalizer(operator, operatorv1.OperatorFinalizer)
It was better before. Always seek to prevent unnecessary updates

2023-07-17 17:54 UTC, avorima commented on internal/controller/operator_controller.go
> +	key := client.ObjectKey{Namespace: obj.GetNamespace(), Name: obj.GetName()}
check out `client.ObjectKeyFromObject`

2023-07-17 17:54 UTC, avorima commented on internal/controller/operator_controller.go
> +	err = r.Delete(ctx, obj)
I like to use `client.IgnoreNotFound` in cases where there is a fire and forget deletion. In this case it's fine, but just remember it exists.

2023-07-18 09:32 UTC, avorima approved these changes

2023-07-18 09:44 UTC, merged